[build]
    command = 'CI= npm run build'
    functions = 'netlify/functions'
    publish = 'build'

[functions]
directory = "/netlify/functions/" 

[[redirects]]
  from = "/works"
  to = "/works"
  status = 200

[[redirects]]
  from = "/posts"
  to = "/posts"
  status = 200

[[redirects]]
  from = "/tutorials"
  to = "/tutorials"
  status = 200
